PUT http://localhost:3000/api/v1/tasks/updateTask/_E3vRnC4tPX4MoLfSW9Wx
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ik9QdW81MDJMcDRvV2dyR3NDd1lLTiIsImlhdCI6MTcwMDYwNTQyMn0.uZfbexHMFEwBMsmhEYpR_XP132eWKYdjR3p5Bv8a8FQ; Path=/; HttpOnly; Secure; SameSite=Strict

{
    "title": "Task title here",
    "description": "Describe task title here",
    "due_date": "04/11/1998",
    "status": "completed"
}

