GET http://localhost:3000/api/v1/tasks/createTask
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlVIdmUxTWRLMVdNX0g3amYwcFU5SiIsImlhdCI6MTcwMDU4MzYyNH0.ipF0B90NdoC7oFob6_oyj4f5gf7xOj3XYaQY_mTLNMQ; Path=/; HttpOnly; Secure; SameSite=Strict

